# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nondv.github.io
email: non.dmitriy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll-based сайт для моих немногочисленных заметок.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nondv.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: Nondv
future: true


header_title: 'Очередной ненужный блог'

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"